// <auto-generated />
using System;
using Lonches_Restaurant.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lonches_Restaurant.Migrations
{
    [DbContext(typeof(LonchesRestaurantContext))]
    partial class LonchesRestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lonches_Restaurant.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<int>("IdMesa")
                        .HasColumnType("int")
                        .HasColumnName("id_mesa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCliente")
                        .HasName("PK__cliente__677F38F5E66C4FBC");

                    b.HasIndex("IdMesa");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.ComandaDetalle", b =>
                {
                    b.Property<int>("IdComandaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comanda_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComandaDetalle"));

                    b.Property<int>("CantidadPedida")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_pedida");

                    b.Property<int>("IdComanda")
                        .HasColumnType("int")
                        .HasColumnName("id_comanda");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observaciones");

                    b.Property<double>("PrecioUnitario")
                        .HasColumnType("float")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdComandaDetalle")
                        .HasName("PK__comanda___BF1F6694B0FC3AB2");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdProducto");

                    b.ToTable("comanda_detalle", (string)null);
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Comandum", b =>
                {
                    b.Property<int>("IdComanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comanda");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComanda"));

                    b.Property<int?>("ComandumIdComanda")
                        .HasColumnType("int");

                    b.Property<int>("Estatus")
                        .HasColumnType("int")
                        .HasColumnName("estatus");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<int>("IdMesa")
                        .HasColumnType("int")
                        .HasColumnName("id_mesa");

                    b.HasKey("IdComanda")
                        .HasName("PK__comanda__6D6D170D711F9C1C");

                    b.HasIndex("ComandumIdComanda");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdMesa");

                    b.ToTable("comanda", (string)null);
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("ApeMaterno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ape_materno");

                    b.Property<string>("ApePaterno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ape_paterno");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("Estatus")
                        .HasColumnType("int")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.Property<int>("Rol")
                        .HasColumnType("int")
                        .HasColumnName("rol");

                    b.HasKey("IdEmpleado")
                        .HasName("PK__empleado__88B51394BC852F41");

                    b.ToTable("empleado", (string)null);
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.EmpleadoMesaIntermedium", b =>
                {
                    b.Property<int>("IdEmpleadoMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empleado_mesa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleadoMesa"));

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<int>("IdMesa")
                        .HasColumnType("int")
                        .HasColumnName("id_mesa");

                    b.HasKey("IdEmpleadoMesa")
                        .HasName("PK__empleado__E0EEFA74198E8502");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdMesa");

                    b.ToTable("empleado_mesa_intermedia", (string)null);
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mesa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMesa"));

                    b.Property<int>("Estatus")
                        .HasColumnType("int")
                        .HasColumnName("estatus");

                    b.Property<string>("NumMesa")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("num_mesa");

                    b.HasKey("IdMesa")
                        .HasName("PK__mesa__68A1E15942B7D0A4");

                    b.ToTable("mesa", (string)null);
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Produccion", b =>
                {
                    b.Property<int>("IdProduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_produccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduccion"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<int>("IdComanda")
                        .HasColumnType("int")
                        .HasColumnName("id_comanda");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.HasKey("IdProduccion")
                        .HasName("PK__producci__9EBBA4335C138B7A");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("produccion", (string)null);
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<int>("Estatus")
                        .HasColumnType("int")
                        .HasColumnName("estatus");

                    b.Property<string>("Fotografia")
                        .HasColumnType("text")
                        .HasColumnName("fotografia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.Property<double>("Precio")
                        .HasColumnType("float")
                        .HasColumnName("precio");

                    b.HasKey("IdProducto")
                        .HasName("PK__producto__FF341C0DF7F68424");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.VentaDetalle", b =>
                {
                    b.Property<int>("IdVentaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_venta_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVentaDetalle"));

                    b.Property<int>("CantidadVendida")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_vendida");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("observaciones");

                    b.Property<double>("PrecioUnitario")
                        .HasColumnType("float")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdVentaDetalle")
                        .HasName("PK__venta_de__7AA8F41BB9F3BF5A");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("venta_detalle", (string)null);
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Ventum", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdComanda")
                        .HasColumnType("int")
                        .HasColumnName("id_comanda");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.HasKey("IdVenta")
                        .HasName("PK__venta__459533BF44ED1F6A");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("venta", (string)null);
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Cliente", b =>
                {
                    b.HasOne("Lonches_Restaurant.Models.Mesa", "IdMesaNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdMesa")
                        .IsRequired()
                        .HasConstraintName("fk_id_cliente_mesa");

                    b.Navigation("IdMesaNavigation");
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.ComandaDetalle", b =>
                {
                    b.HasOne("Lonches_Restaurant.Models.Comandum", "IdComandaNavigation")
                        .WithMany("ComandaDetalles")
                        .HasForeignKey("IdComanda")
                        .IsRequired()
                        .HasConstraintName("fk_id_comanda_comanda");

                    b.HasOne("Lonches_Restaurant.Models.Producto", "IdProductoNavigation")
                        .WithMany("ComandaDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("fk_id_comanda_producto");

                    b.Navigation("IdComandaNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Comandum", b =>
                {
                    b.HasOne("Lonches_Restaurant.Models.Comandum", null)
                        .WithMany("Comanda")
                        .HasForeignKey("ComandumIdComanda");

                    b.HasOne("Lonches_Restaurant.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Comanda")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("fk_id_comanda_cliente");

                    b.HasOne("Lonches_Restaurant.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Comanda")
                        .HasForeignKey("IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("fk_id_comanda_empleado");

                    b.HasOne("Lonches_Restaurant.Models.Mesa", "IdMesaNavigation")
                        .WithMany("Comanda")
                        .HasForeignKey("IdMesa")
                        .IsRequired()
                        .HasConstraintName("fk_id_comanda_mesa");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEmpleadoNavigation");

                    b.Navigation("IdMesaNavigation");
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.EmpleadoMesaIntermedium", b =>
                {
                    b.HasOne("Lonches_Restaurant.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("EmpleadoMesaIntermedia")
                        .HasForeignKey("IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("fk_id_empleado_mesa");

                    b.HasOne("Lonches_Restaurant.Models.Mesa", "IdMesaNavigation")
                        .WithMany("EmpleadoMesaIntermedia")
                        .HasForeignKey("IdMesa")
                        .IsRequired()
                        .HasConstraintName("fk_id_mesa_empleado");

                    b.Navigation("IdEmpleadoNavigation");

                    b.Navigation("IdMesaNavigation");
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Produccion", b =>
                {
                    b.HasOne("Lonches_Restaurant.Models.Comandum", "IdComandaNavigation")
                        .WithMany("Produccions")
                        .HasForeignKey("IdComanda")
                        .IsRequired()
                        .HasConstraintName("fk_id_produccion_comanda");

                    b.HasOne("Lonches_Restaurant.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Produccions")
                        .HasForeignKey("IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("fk_id_produccion_empleado");

                    b.Navigation("IdComandaNavigation");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.VentaDetalle", b =>
                {
                    b.HasOne("Lonches_Restaurant.Models.Producto", "IdProductoNavigation")
                        .WithMany("VentaDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("fk_id_venta_producto");

                    b.HasOne("Lonches_Restaurant.Models.Ventum", "IdVentaNavigation")
                        .WithMany("VentaDetalles")
                        .HasForeignKey("IdVenta")
                        .IsRequired()
                        .HasConstraintName("fk_id_venta_venta");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Ventum", b =>
                {
                    b.HasOne("Lonches_Restaurant.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("fk_id_venta_cliente");

                    b.HasOne("Lonches_Restaurant.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("fk_id_venta_empleado");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Cliente", b =>
                {
                    b.Navigation("Comanda");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Comandum", b =>
                {
                    b.Navigation("Comanda");

                    b.Navigation("ComandaDetalles");

                    b.Navigation("Produccions");
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Empleado", b =>
                {
                    b.Navigation("Comanda");

                    b.Navigation("EmpleadoMesaIntermedia");

                    b.Navigation("Produccions");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Mesa", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Comanda");

                    b.Navigation("EmpleadoMesaIntermedia");
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Producto", b =>
                {
                    b.Navigation("ComandaDetalles");

                    b.Navigation("VentaDetalles");
                });

            modelBuilder.Entity("Lonches_Restaurant.Models.Ventum", b =>
                {
                    b.Navigation("VentaDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
